DELETE FROM rol_privilegio
WHERE rp_fk_privilegio IN ( SELECT privilegio_codigo
                            FROM privilegio
                            WHERE privilegio_tipo LIKE 'Premio' 
                            OR privilegio_tipo LIKE 'Clasificacion' 
                            OR privilegio_tipo LIKE 'Categoria' 
                            OR privilegio_tipo LIKE 'Servido' 
                            OR privilegio_tipo LIKE 'Sabor' 
                            OR privilegio_tipo LIKE 'Aroma' 
                            OR privilegio_tipo LIKE 'Color' 
                            OR privilegio_tipo LIKE 'Ingrediente' 
                            OR privilegio_tipo LIKE 'Barrica' 
                            OR privilegio_tipo LIKE 'Añejamiento' 
                            OR privilegio_tipo LIKE 'Destilacion' 
                            OR privilegio_tipo LIKE 'Fermentacion' 
                            OR privilegio_tipo LIKE 'Diario Ronero' 
                            OR privilegio_tipo LIKE 'Tapa' 
                            OR privilegio_tipo LIKE 'Caja' 
                            OR privilegio_tipo LIKE 'Botella' 
                            OR privilegio_tipo LIKE 'Cata' 
                            OR privilegio_tipo LIKE 'Evento' 
                            OR privilegio_tipo LIKE 'Pago Entrada' 
                            OR privilegio_tipo LIKE 'Inventario sede' 
                            OR privilegio_tipo LIKE 'Inventario Eventos' 
                            OR privilegio_tipo LIKE 'Ficha Afiliacion'
                            OR privilegio_tipo LIKE 'Pago de Afiliacion'
                          );

DELETE FROM privilegio
WHERE privilegio_tipo LIKE 'Premio' 
               OR privilegio_tipo LIKE 'Clasificacion' 
               OR privilegio_tipo LIKE 'Categoria' 
               OR privilegio_tipo LIKE 'Servido' 
               OR privilegio_tipo LIKE 'Sabor' 
               OR privilegio_tipo LIKE 'Aroma' 
               OR privilegio_tipo LIKE 'Color' 
               OR privilegio_tipo LIKE 'Ingrediente' 
               OR privilegio_tipo LIKE 'Barrica' 
               OR privilegio_tipo LIKE 'Añejamiento' 
               OR privilegio_tipo LIKE 'Destilacion' 
               OR privilegio_tipo LIKE 'Fermentacion' 
               OR privilegio_tipo LIKE 'Diario Ronero' 
               OR privilegio_tipo LIKE 'Tapa' 
               OR privilegio_tipo LIKE 'Caja' 
               OR privilegio_tipo LIKE 'Botella' 
               OR privilegio_tipo LIKE 'Cata' 
               OR privilegio_tipo LIKE 'Evento' 
               OR privilegio_tipo LIKE 'Pago Entrada' 
               OR privilegio_tipo LIKE 'Inventario sede' 
               OR privilegio_tipo LIKE 'Inventario Eventos' 
               OR privilegio_tipo LIKE 'Ficha Afiliacion'
               OR privilegio_tipo LIKE 'Pago de Afiliacion'